---
- name: Install nvm fish support
  shell:
    cmd: fisher install edc/bass
    executable: /usr/bin/fish

- name: Add nvm function
  template:
    src: templates/nvm.fish
    dest: "/home/{{ ansible_user }}/.config/fish/functions/nvm.fish"
