---
- hosts: all
  connection: local
  roles:
    - role: install-packages
    - role: magicmouse
    - role: docker
    - role: nvm
    - role: dual-screen
    - role: ssh-key
    - role: google-drive
    - role: vim-arrow-keys
    - role: dotfiles
    - role: betterlockscreen
