---
- name: Create the mkinitcpio.conf file
  become: yes
  template:
    src: templates/mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
    owner: root
    group: root
    mode: 0644
  notify: run mkinitcpio

- name: Create the grub default config file
  become: yes
  template:
    src: templates/grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
  notify: regenerate grub
