- name: Setup application autostart
  template:
    src: templates/application.desktop
    dest: "/home/{{ ansible_user }}/.config/autostart/{{ item.filename }}.desktop"
  with_items:
    - "{{ autostart_commands }}"
