---
pacman_packages:
  - base
  - base-devel
  - pacman-contrib
  - vim
  - git
  - vagrant
  - virtualbox
  - nfs-utils
  - ttf-jetbrains-mono
  - libsecret
  - gnupg
  - pcsclite
  - ccid
  - hopenpgp-tools
  - yubikey-personalization
  - xclip
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - alsa-firmware
  - alsa-lib
  - alsa-plugins
  - alsa-utils
  - gstreamer
  - sddm
  - tlp
  - unrar
  - zip
  - unzip
  - xdg-user-dirs
  - ntp
  - xorg-xinput
  - xsel
  - slock
  - fish
  - ttf-roboto
  - ttf-roboto-mono
  - bluez
  - bluez-libs
  - gnome-keyring
  - networkmanager
  - arc-gtk-theme
  - baobab
  - evince
  - file-roller
  - gnome-backgrounds
  - gnome-characters
  - gnome-color-manager
  - gnome-control-center
  - gnome-disk-utility
  - gnome-font-viewer
  - gnome-keyring
  - gnome-menus
  - gnome-screenshot
  - gnome-session
  - gnome-settings-daemon
  - gnome-shell
  - gnome-shell-extensions
  - gnome-system-monitor
  - gnome-user-docs
  - gnome-video-effects
  - grilo-plugins
  - gvfs
  - gvfs-afc
  - gvfs-goa
  - gvfs-google
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-nfs
  - gvfs-smb
  - mutter
  - nautilus
  - sushi
  - tracker
  - tracker-miners
  - tracker3-miners
  - vino
  - xdg-user-dirs-gtk
  - sxhkd
  - python-pip
  - gimp
  - docker-compose
  - tldr
  - bluez-utils
