---
yay_packages:
  - whatsapp-nativefier
  - 1password
  - visual-studio-code-bin
  - brave-bin
  - insomnia-bin
  - discord
  - mattermost-desktop-bin
  - yubikey-manager
  - i3lock-fancy
  - xss-lock-git
  - chrome-gnome-shell
  - gnome-tweaks
  - gnome-terminal-transparency
  - ulauncher
  - jrnl
  - spotify
  - notion-app-enhanced
  - nvm
  - act

snap_packages:
  - code
  - whatsapp-for-linux
  - 1password
  - brave
  - insomnia
  - okular
  - discord
  - mattermost-desktop
  - olivia
  - notion-snap
