---
- name: Create config directory
  file:
    path: "/home/{{ ansible_user }}/.config/sxhkd"
    state: directory

- name: Create sxhkdd config file
  template:
    src: templates/sxhkdrc
    dest: "/home/{{ ansible_user }}/.config/sxhkd/sxhkdrc"
