---
- name: Create .ssh directory
  file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory
    mode: 0755

- name: Copy private ssh key
  become: yes
  template:
    src: templates/id_rsa.j2
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  notify: add key to agent

- name: Copy public ssh key
  become: yes
  template:
    src: templates/id_rsa.pub.j2
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  notify: add key to agent

- name: Evaluating the authentication agent & adding the key...
  shell: |
    eval "$(ssh-agent)"
    ssh-add ~/.ssh/id_rsa
