---
- name: Add Apt GPG keys
  become: yes
  apt_key:
    url: "{{ item }}"
  with_items: "{{ apt_keys }}"

- name: Add repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repositories }}"

- name: Install aptitude packages
  become: yes
  apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ apt_packages }}"

- name: Install snap packages
  become: yes
  snap:
    name: "{{ snap_packages }}"
