#!/bin/bash
export DISPLAY=:0.0
 
function connect(){
  xrandr --output DP-1 --auto --output eDP-1 --off
}
  
function disconnect(){
  xrandr --output DP-1 --off
}
   
ps -e | grep Xorg && (xrandr | grep "^DP-1 connected" && connect > /dev/null 2> /home/stan/hp_monitor.log || disconnect)
