---
- name: Create config directory
  file:
    path: "/home/{{ ansible_user }}/.config/awesome"
    state: directory
    mode: 0755

- name: Clone the themes repository
  git:
    repo: https://github.com/lcpz/awesome-copycats.git
    dest: "/home/{{ ansible_user }}/.config/awesome/awesome-copycat"
    depth: 1

- name: Link the themes directory
  file:
    src: "/home/{{ ansible_user }}/.config/awesome/awesome-copycat/themes"
    dest: "/home/{{ ansible_user }}/.config/awesome/themes"
    state: link

- name: Setup config
  copy:
    src: templates/rc.lua
    dest: "/home/{{ ansible_user }}/.config/awesome/rc.lua"

- name: Setup theme
  copy:
    src: templates/theme.lua
    dest: "/home/{{ ansible_user }}/.config/awesome/theme.lua"

- name: Setup xprofile
  copy:
    src: templates/xprofile
    dest: "/home/{{ ansible_user }}/.xprofile"
    mode: 0755
